In [ ]:
import numpy as np

In [5]:
names=["Michael","Hart"]
names.append("Richard")

print(len(names))

names+=["Abi","Kevin"]

print(names)
more_names=[]
more_names=list()
stuff=[]
print(stuff)

stuff.append(1)
stuff.append(["hi","bye"])

stuff.append(-0.12)
stuff.append(None)

print(stuff)


3
['Michael', 'Hart', 'Richard', 'Abi', 'Kevin']
[]
[1, ['hi', 'bye'], -0.12, None]


In [ ]:
numbers=[0,1,2,3,4,5,6]
print(numbers[0:3])

print(numbers[:3])
print(numbers[5:])

print(*numbers)

print(numbers[-1])

print(numbers[-3:])

print(numbers[3:-2])


[0, 1, 2]
[0, 1, 2]
[5, 6]
0 1 2 3 4 5 6
6
[4, 5, 6]
[3, 4]


In [8]:
names=("Michael","Hart")
try:
    names[0]="Michael"
except:
    print("tunple is immutable")

names=tuple()
single=(10)
print(single)
print(type(single))


tunple is immutable
10
<class 'int'>


In [10]:
di1={}
di2=dict()

phonebook={"Michael":"12-37"}
phonebook["Hart"]="34-23"
if "Michael" in phonebook:
    print(phonebook["Michael"])
if "Kevin" in phonebook:
    print(phonebook["Kevin"])
print(phonebook.get("Hart","not found"))

phonebook.__delitem__("Michael")

print(phonebook)


12-37
34-23
{'Hart': '34-23'}


In [11]:
for i in range(5):
    print(i)

names=["Michael","Hart","Richard"]

for i in range(len(names)):
    print(i,names[i])
for i,j in enumerate(names):
    print(i,j) 

phonebook={"Michael":"12-37","Hart":"34-23"}

for name,number in phonebook.items():
    print(name,number)
    print("---")

0
1
2
3
4
0 Michael
1 Hart
2 Richard
0 Michael
1 Hart
2 Richard
Michael 12-37
---
Hart 34-23
---


In [15]:
x=np.array([1,2,3])
y=np.array([3,4,5])
z=np.array([[6,7],[8,9]])
print(x.shape)
print(y.shape)
print(z.shape)
print(z)

(3,)
(3,)
(2, 2)
[[6 7]
 [8 9]]


In [12]:
import numpy as np

a=np.arange(10)

b=a.reshape(5,2)
print(a)
print(b)


[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [16]:
x=np.array([[1,2],[3,4],[5,6]])

x1=np.max(x,axis=1)
x2=np.max(x,axis=1,keepdims=True)
print(x1)
print(x2)
print(x1.shape)
print(x2.shape)

A=np.array([[1,2],[3,4]])


B=np.array([[3,3],[3,3]])

print(A)
print(B)
print(A*B)


[2 4 6]
[[2]
 [4]
 [6]]
(3,)
(3, 1)
[[1 2]
 [3 4]]
[[3 3]
 [3 3]]
[[ 3  6]
 [ 9 12]]


In [17]:
print(A@B)
print(np.matmul(A,B))

[[ 9  9]
 [21 21]]
[[ 9  9]
 [21 21]]


In [ ]:
u=np.array([1,2,3])
v=np.array([1,10,100])
print(np.dot(u,v))
print(u.dot(v))

w=np.array([[1,2],[3,4],[5,6]])
v=np.array([1,10,100])
print(w.shape)
print(v.shape)
print(np.dot(v,w))
print(np.dot(v,w).shape)
try:
    print(np.dot(w,v))
except:
    print("error")


print(np.dot(w.T,v))

321
321
(3, 2)
(3,)
[531 642]
(2,)
error
[531 642]


In [26]:
x=np.random.randn(3,4)
print(x)

print(x[:])
print(x[np.array([0,2]),:])
print(x[1,1:3])
print(x[x>0.5])
print(x[:,:,np.newaxis])

[[-0.47246388  0.39571083  1.21587668 -0.51885396]
 [-0.83249857  0.39106683  0.43136676  0.40430606]
 [-0.67235425  0.4708213   1.82052865 -1.36772108]]
[[-0.47246388  0.39571083  1.21587668 -0.51885396]
 [-0.83249857  0.39106683  0.43136676  0.40430606]
 [-0.67235425  0.4708213   1.82052865 -1.36772108]]
[[-0.47246388  0.39571083  1.21587668 -0.51885396]
 [-0.67235425  0.4708213   1.82052865 -1.36772108]]
[0.39106683 0.43136676]
[1.21587668 1.82052865]
[[[-0.47246388]
  [ 0.39571083]
  [ 1.21587668]
  [-0.51885396]]

 [[-0.83249857]
  [ 0.39106683]
  [ 0.43136676]
  [ 0.40430606]]

 [[-0.67235425]
  [ 0.4708213 ]
  [ 1.82052865]
  [-1.36772108]]]


In [5]:
import numpy as np
x=np.random.randn(3,4)

y=np.random.randn(3,1)
z=np.random.randn(1,4)
s=x+y
p=x*z
print(x)
print(y)
print(s)
print(z)
print(p)

a=np.zeros((3,3))
b=np.array([[1,2,3]])
print(a+b)

a=np.random.randn(3,4)
b=np.random.randn(3,1)

c=np.random.randn(3,1)
result1=b+b.T
result2=a+c
result3=b+c
print(result1.shape)
print(result2.shape)
print(result3.shape)

[[-1.95652185 -0.76571979 -0.26493569 -1.11493464]
 [-1.32130576  1.03127649 -0.49331724  0.31082847]
 [ 0.79030599  0.10344738  0.20915954 -0.38081716]]
[[-1.25088209]
 [-1.32366591]
 [ 0.40896144]]
[[-3.20740395 -2.01660188 -1.51581778 -2.36581673]
 [-2.64497167 -0.29238942 -1.81698315 -1.01283744]
 [ 1.19926743  0.51240882  0.61812098  0.02814428]]
[[ 1.55184365 -2.03908066  1.09944195  1.24755659]]
[[-3.03621602  1.56136441 -0.29128141 -1.39094406]
 [-2.05045996 -2.10285595 -0.54237366  0.38777611]
 [ 1.22643134 -0.21093756  0.22995878 -0.47509096]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
(3, 3)
(3, 4)
(3, 1)


In [15]:
x=np.random.randn(1000,1000)


In [17]:
%%timeit
for i in range(100,1000):
    for j in range(1000):
        x[i,j]+=5
print(x)

[[-0.50635562  1.50003283  0.26514973 ...  1.58701518 -1.93024044
  -0.0187493 ]
 [ 0.06548675  0.85578212  0.42356405 ... -1.53415102  0.0912621
   1.02654516]
 [-1.3022493  -0.17451482  0.43640134 ...  2.87977306 -0.64124019
   1.1230413 ]
 ...
 [ 6.89275437  5.09748386  4.72026928 ...  3.78809231  7.50141388
   5.07907196]
 [ 4.15453932  5.29738159  3.70059694 ...  5.43358349  5.06719852
   5.98744009]
 [ 4.99054072  5.6669175   4.13453084 ...  6.95869244  4.19888236
   3.44557815]]
[[-0.50635562  1.50003283  0.26514973 ...  1.58701518 -1.93024044
  -0.0187493 ]
 [ 0.06548675  0.85578212  0.42356405 ... -1.53415102  0.0912621
   1.02654516]
 [-1.3022493  -0.17451482  0.43640134 ...  2.87977306 -0.64124019
   1.1230413 ]
 ...
 [11.89275437 10.09748386  9.72026928 ...  8.78809231 12.50141388
  10.07907196]
 [ 9.15453932 10.29738159  8.70059694 ... 10.43358349 10.06719852
  10.98744009]
 [ 9.99054072 10.6669175   9.13453084 ... 11.95869244  9.19888236
   8.44557815]]
[[-0.50635562  1.5

In [16]:
x=np.random.randn(1000,1000)


In [18]:
%%timeit
x[100:1000,:]+=5

195 μs ± 11.9 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
